# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/CPU/CPU.cache/wt [current_project]
set_property parent.project_path E:/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/CPU/CPU.srcs/sources_1/new/SegLED.v
  E:/CPU/CPU.srcs/sources_1/new/Select_32.v
  E:/CPU/CPU.srcs/sources_1/new/LEDdisplay.v
  E:/CPU/CPU.srcs/sources_1/new/Select_5.v
  E:/CPU/CPU.srcs/sources_1/new/Register.v
  E:/CPU/CPU.srcs/sources_1/new/PC_Control.v
  E:/CPU/CPU.srcs/sources_1/new/PC.v
  E:/CPU/CPU.srcs/sources_1/new/InsMEM.v
  E:/CPU/CPU.srcs/sources_1/new/Extend.v
  E:/CPU/CPU.srcs/sources_1/new/DataMEM.v
  E:/CPU/CPU.srcs/sources_1/new/Control_unit.v
  E:/CPU/CPU.srcs/sources_1/new/ALU.v
  E:/CPU/CPU.srcs/sources_1/new/CPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/CPU/CPU.srcs/constrs_1/new/CPU.xdc
set_property used_in_implementation false [get_files E:/CPU/CPU.srcs/constrs_1/new/CPU.xdc]


synth_design -top CPU -part xc7a35tcpg236-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
